version: "3.7"
services:

  users-service:
    build:
      context: ./users-service
      dockerfile: ./src/main/resources/deploy/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - users-postgres-db

  users-postgres-db:
    container_name: users-postgres-db
    image: postgres:latest
    volumes:
      - users-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb

volumes:
  users-data: